# Generated by Django 5.0.1 on 2024-01-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("friend_request", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="receiver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="requester",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requester_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
