# Generated by Django 5.0.1 on 2024-01-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend_request", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Pending"), (1, "Accepted"), (2, "Rejected")], default=0
            ),
        ),
    ]
