# Generated by Django 5.0.1 on 2024-01-24 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend_request", "0002_initial"),
        ("user", "0002_user_friend_request_user_friend_request_receiver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="friend_request",
        ),
        migrations.RemoveField(
            model_name="user",
            name="friend_request_receiver",
        ),
        migrations.AddField(
            model_name="user",
            name="friend_requests_received",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_friend_requests_received",
                to="friend_request.friendrequest",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="friend_requests_sent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_friend_requests_sent",
                to="friend_request.friendrequest",
            ),
        ),
    ]
