# Generated by Django 5.0.1 on 2024-01-24 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_user_friend_request_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="friend_requests_received",
        ),
        migrations.RemoveField(
            model_name="user",
            name="friend_requests_sent",
        ),
    ]
