# Generated by Django 5.0.1 on 2024-01-25 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_user_friend_requests_received_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_followers",
            field=models.ManyToManyField(
                blank=True, related_name="user_followed_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
