# Generated by Django 5.0.1 on 2024-01-25 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_user_followers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_followers",
            new_name="user_following",
        ),
    ]
