# Generated by Django 5.0.1 on 2024-01-25 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_rename_user_followers_user_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="custom_users_following",
        ),
    ]
